### ISSUE TITLE
Filebeat keeps crashing

### ISSUE THREAD

**Issue by tnmch** [muenchhausen/docker-squidguard-elk#3]
When the container start , it keeps crashing due to error 

> "error" : "Content-Type header [application/x-www-form-urlencoded] is not supported"

I think the problem come from entrypoint.sh "curl"

https://stackoverflow.com/questions/47544966/elasticsearch-content-type-header-application-x-www-form-urlencoded-is-not-s

**Comment by muenchhausen** [comment]
thanks for your analysis - I‘ll try it in weekend
